### ISSUE TITLE
KeyError: 'Helen'

### ISSUE THREAD

**Issue by getengqing** [SinaHonari/RCN#4]
Hello,  when I train the denoise model, I got the error. Can you how solve it?
error is this:  File "RCN/models/create_procs.py", line 88, in get_data
                    Helen_set = test_set_300W['Helen']
                    KeyError: 'Helen'

**Comment by SinaHonari** [comment]
What do you get when you do the following?

test_set_300W.keys()

**Comment by getengqing** [comment]
3Q, I solved it!

**Comment by sainisanjay** [comment]
> 3Q, I solved it!

How did you solve? i am getting same error.
